### PR TITLE
Bumb nix to 2.30.1

### PR DESCRIPTION
**Pull request by rockdaboot**

### CODE REVIEW

**Comment by rockdaboot** [comment]
> LGTM, for whatever that is worth. :D

Haha, this was just a quick experiment about why the CI fails with the dependabot PRs. It turned out that several dependencies introduced breaking changes. Nevermind :)

**Comment by athre0z** [comment]
Dependabot PRs fail because the tool produces incorrect PRs: it only updates `Cargo.toml`, but not `Cargo.lock`. This is pretty bad practice, since it's not predictable which actual library version will be used in the end, since Lock is re-generated based on latest matching for everyone building it if the lock is out of date. Maybe the bot can be configured to also update the lock?

**Comment by rockdaboot** [comment]
Hm, I did some of the dependabot updates locally and it looks like Cargo.lock was updated correctly. Still see plenty of errors due to breaking API changes. Like
```
error[E0061]: this method takes 5 arguments but 4 arguments were supplied
   --> src/ui/util.rs:140:21
    |
140 |             painter.rect(tile, 0.0, color, Stroke::NONE);
    |                     ^^^^-------------------------------- argument #5 of type `StrokeKind` is missing
    |
```
